### ISSUE TITLE
commit intermidiate result of digital algorithm martakarta

### ISSUE THREAD

**Issue by ff6347** [FH-Potsdam/steel-ant-input-output#10]

**Comment by martakarta** [comment]
/Users/martakarta/Desktop/fhp/wise1516/einaus/projekt1/digital/algotithmus Kopie/p5js-starter-kit

**Comment by ff6347** [comment]
Closed by https://github.com/FH-Potsdam/steel-ant-input-output/commit/8a27ec7d60cf3b8426bab4ef8ae2696951cae6ef
