### ISSUE TITLE
Add index.html

### ISSUE THREAD

**Issue by ff6347** [FH-Potsdam/steel-ant-input-output#21]
Also you need to add an index HTML file so it is possible to preview your code.

**Comment by ff6347** [comment]
Sorry to say that. But your HTML is still wrong. The lib is missing

**Comment by vogelino** [comment]
I thought you wanted us to use a CDN but I got you wrong apparently 😕. I'll update it then! Sorry!

**Comment by ff6347** [comment]
Well. CDN is cooler but it doesn't matter right now
