### ISSUE TITLE
commit intermidiate result of digital algorithm josues

### ISSUE THREAD

**Issue by ff6347** [FH-Potsdam/steel-ant-input-output#4]

**Comment by ff6347** [comment]
hi @josues the lib is missing. add a CDN or add the lib

**Comment by josues** [comment]
Okay ich denke jetzt ist sie drin. Ich weiß allerdings nicht wie [steel-ant-input-output/JoshuasOrdner](https://github.com/FH-Potsdam/steel-ant-input-output/tree/master/JoshuasOrdner) lösche..

**Comment by josues** [comment]
Geschafft.

**Comment by ff6347** [comment]
Top
